In [1]:
import numpy as np
import scipy.io
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas as pd
import random
import time 

import os
from pathlib import Path

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split, LeaveOneOut, GroupKFold
from sklearn.svm import LinearSVC, SVR
from sklearn.feature_selection import SelectFromModel
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV
from sklearn.metrics import balanced_accuracy_score, f1_score

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler

from sklearn.utils import shuffle

from make_classification import *

# Import and prepare dataset

In [2]:
path_labels = '../Dataset/'
labels = pd.read_csv(path_labels+'labels.txt', sep=",", header=0, index_col=0)
labels.head()

3class  binary-stress  binary-relax  binary-valence  \
subject/task                                                          
2ea4_Breathing       0              0             1             0.0   
2ea4_Counting1       1              1             0             0.0   
2ea4_Counting2       1              1             0             0.0   
2ea4_Counting3       1              1             0             0.0   
2ea4_Math            1              1             1             0.0   

                binary-arousal  
subject/task                    
2ea4_Breathing             0.0  
2ea4_Counting1             1.0  
2ea4_Counting2             1.0  
2ea4_Counting3             1.0  
2ea4_Math                  1.0

In [3]:
y = labels['binary-stress']
y.value_counts()

1    360
0    331
Name: binary-stress, dtype: int64

In [4]:
x_ecg = pd.read_csv('Features/ecg_features.csv', sep=",", header=0, index_col=0)
x_eda = pd.read_csv('Features/eda_features.csv', sep=",", header=0, index_col=0)
x_resp = pd.read_csv('Features/resp_features.csv', sep=",", header=0, index_col=0)

# --------- TO FIX: Remove rows without a label --------------#
x_ecg = x_ecg.loc[list(labels.index)]
x_eda = x_eda.loc[list(labels.index)]
x_resp = x_resp.loc[list(labels.index)]
# ------------------------------------------------------------#

In [5]:
x = pd.read_csv('Features/all_physiological_features.csv', sep=",", header=0, index_col=0)
x.head(5)

meanHR      minHR      maxHR       sdHR     modeHR  \
2ea4_Baseline   63.430940  57.034221  79.575597   4.686314  22.541376   
2ea4_Breathing  61.712465  45.871560  84.269663  11.008515  38.398103   
2ea4_Counting1  70.649419  58.252427  82.872928   5.750703  24.620501   
2ea4_Counting2  63.913828  52.910053  79.787234   5.890798  26.877181   
2ea4_Counting3  64.321357  49.751244  78.534031   5.908397  28.782788   

                      nNN       meanNN        SDSD        CVNN      SDNN  ...  \
2ea4_Baseline   62.000000   950.677419   42.033401   64.843179  0.068207  ...   
2ea4_Breathing  59.666667  1002.893855  106.659486  173.316531  0.172816  ...   
2ea4_Counting1  69.000000   855.101449   43.670598   72.095377  0.084312  ...   
2ea4_Counting2  63.000000   946.476190   58.622906   84.207389  0.088969  ...   
2ea4_Counting3  62.000000   941.032258   39.985888   90.192441  0.095844  ...   

                 VHF_rsp  LF/HF_rsp    rLF_rsp    rHF_rsp  peakLF_rsp  \
2ea4_Baseline   2.403554   1.025407  50.627207  49.372793    0.131387   
2ea4_Breathing  9.995773   2.720270  73.120232  26.879768    0.117188   
2ea4_Counting1  0.923779   1.881455  65.295311  34.704689    0.086957   
2ea4_Counting2  0.292025  15.878445  94.075284   5.924716    0.082192   
2ea4_Counting3  1.063001  33.239731  97.079416   2.920584    0.093750   

                peakHF_rsp      SD1_rrv     SD2_rrv  SD1SD2_rrv  apEn_rrv  
2ea4_Baseline     0.175182   816.718056  333.265493    2.450653  0.105361  
2ea4_Breathing    0.164062  1119.779881  647.574415    1.729191  0.013791  
2ea4_Counting1    0.173913   560.140756  681.563788    0.821846  0.105361  
2ea4_Counting2    0.164384   538.632539  525.776932    1.024451  0.105361  
2ea4_Counting3    0.187500   908.089478  816.368158    1.112353  0.117783  

[5 rows x 132 columns]

#### Pre-processing of the data

In [6]:
"""
# remove the inf values and columns with more than 20% missing data
x.replace([np.inf, -np.inf], np.nan, inplace=True)
nan_cols = [i for i in x.columns if x[i].isnull().sum() > 0.2*len(x)]
x.drop(columns=nan_cols, inplace=True)
"""

# --------- TO FIX: Remove rows without a label --------------#
x = x.loc[list(labels.index)]
# ------------------------------------------------------------#

# Classification

Feature selection using L1 penalty or Recursive Feature Elimination (RFE). The optimal number of features is determined using RFECV. Several models are tested: Logistic Regression, Decision Trees, Random Forests, K neares neighbors, Adaboost, GradientBoosting, and Multi Layer Perceptron. 

The models are fitted 10 times, and the average scores over 10 repetitions are reported.

## One dataset (example: only on ECG features database) 

In [8]:
feature_selector= "l1"
list_classif = [#LogisticRegression(max_iter=5000, random_state=0),
                #DecisionTreeClassifier(random_state=0), 
                RandomForestClassifier(max_depth=5, random_state=0), 
                #KNeighborsClassifier(n_neighbors=3), 
                #AdaBoostClassifier(n_estimators=100, random_state=0), 
                #GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=2, random_state=0),
                MLPClassifier(random_state=0, max_iter=5000)]
n_splits=10

In [10]:
res, conf = make_nclassif(x_ecg, y, n_splits=n_splits, 
                    feature_selector=feature_selector, 
                    list_classifiers = list_classif)
avg_res(res)

Split  1/10
Split  2/10
Split  3/10
Split  4/10
Split  5/10
Split  6/10
Split  7/10
Split  8/10
Split  9/10
Split 10/10


f1-score  accuracy      time
classifier                                          
MLPClassifier           0.671666  0.673500  3.734108
RandomForestClassifier  0.672363  0.680108  1.327348

In [14]:
conf

[array([[21, 10],
        [22, 24]]),
 array([[21, 10],
        [18, 28]]),
 array([[18, 18],
        [ 5, 35]]),
 array([[25, 11],
        [ 7, 33]]),
 array([[18, 16],
        [ 8, 34]]),
 array([[17, 17],
        [ 8, 34]]),
 array([[22, 14],
        [ 4, 26]]),
 array([[25, 11],
        [ 9, 21]]),
 array([[15, 13],
        [11, 27]]),
 array([[18, 10],
        [ 9, 29]]),
 array([[18, 16],
        [ 6, 26]]),
 array([[18, 16],
        [ 8, 24]]),
 array([[21, 19],
        [ 8, 18]]),
 array([[22, 18],
        [ 8, 18]]),
 array([[21, 11],
        [ 4, 30]]),
 array([[23,  9],
        [10, 24]]),
 array([[15,  5],
        [10, 36]]),
 array([[12,  8],
        [19, 27]]),
 array([[18, 22],
        [ 3, 23]]),
 array([[23, 17],
        [ 4, 22]])]

In [13]:
np.mean(conf, axis=0)

array([[19.55, 13.55],
       [ 9.05, 26.95]])

## Comparison of several datasets (example: ECG only, EDA only, respiration only, and all 3 modalities)

In [15]:
list_datasets = [('ECG',x_ecg), ('EDA',x_eda), ('Resp',x_resp), ('all', x)]

In [16]:
res_benchmark = benchmark_nrep(list_datasets, y, 
                               n_splits=n_splits, 
                               feature_selector=feature_selector, 
                               list_classifiers = list_classif, verbose=False)

#### ECG results

In [17]:
avg_res(res_benchmark['ECG'])

f1-score  accuracy      time
classifier                                          
MLPClassifier           0.671666  0.673500  4.378946
RandomForestClassifier  0.672363  0.680108  1.368795

#### EDA results

In [18]:
avg_res(res_benchmark['EDA'])

f1-score  accuracy      time
classifier                                          
MLPClassifier           0.615173  0.621367  2.955061
RandomForestClassifier  0.627674  0.647164  0.715421

#### Respiration results

In [19]:
avg_res(res_benchmark['Resp'])

f1-score  accuracy      time
classifier                                          
MLPClassifier           0.650243  0.654320  5.842921
RandomForestClassifier  0.702040  0.709686  2.560822

#### All modalities combined

In [20]:
avg_res(res_benchmark['all'])

f1-score  accuracy       time
classifier                                           
MLPClassifier           0.628752  0.636103  13.572231
RandomForestClassifier  0.691889  0.700457   8.966039

# Test - using random splits instead of grouped by subjects
#### All modalities

In [ ]:
resrandom = make_nclassif_random_splits(x, y, n_splits=n_splits, 
                                        feature_selector=feature_selector, 
                                        list_classifiers = list_classif)
avg_res(resrandom)

#### ECG only

In [ ]:
resrandomecg = make_nclassif_random_splits(x_ecg, y, n_splits=n_splits, 
                                        feature_selector=feature_selector, 
                                        list_classifiers = list_classif, verbose=False)
avg_res(resrandomecg)